# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inc\main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(950, 910)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(950, 0))
        MainWindow.setStyleSheet(_fromUtf8("background-color:#333; color:white;"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(640, 640))
        self.centralwidget.setStyleSheet(_fromUtf8("QWidget {background-color:#333}"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.layJobData = QtGui.QHBoxLayout()
        self.layJobData.setObjectName(_fromUtf8("layJobData"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("color:#888"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_10.addWidget(self.label_4)
        self.edtDate = QtGui.QDateEdit(self.centralwidget)
        self.edtDate.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDate.sizePolicy().hasHeightForWidth())
        self.edtDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edtDate.setFont(font)
        self.edtDate.setStyleSheet(_fromUtf8("background-color: black; color:white; font-size:12pt; border: 1px solid #888"))
        self.edtDate.setAlignment(QtCore.Qt.AlignCenter)
        self.edtDate.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.verticalLayout_10.addWidget(self.edtDate)
        self.layJobData.addLayout(self.verticalLayout_10)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color:#888"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_7.addWidget(self.label)
        self.edtCustomerName = QtGui.QLineEdit(self.centralwidget)
        self.edtCustomerName.setMouseTracking(False)
        self.edtCustomerName.setAutoFillBackground(False)
        self.edtCustomerName.setStyleSheet(_fromUtf8("background-color:black; color:white; font-size:12pt; border:  1px solid #888"))
        self.edtCustomerName.setAlignment(QtCore.Qt.AlignCenter)
        self.edtCustomerName.setPlaceholderText(_fromUtf8(""))
        self.edtCustomerName.setObjectName(_fromUtf8("edtCustomerName"))
        self.verticalLayout_7.addWidget(self.edtCustomerName)
        self.layJobData.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color:#888"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_8.addWidget(self.label_2)
        self.edtLocation = QtGui.QLineEdit(self.centralwidget)
        self.edtLocation.setMouseTracking(False)
        self.edtLocation.setAutoFillBackground(False)
        self.edtLocation.setStyleSheet(_fromUtf8("background-color:black; color:white; font-size:12pt; border:  1px solid #888"))
        self.edtLocation.setAlignment(QtCore.Qt.AlignCenter)
        self.edtLocation.setPlaceholderText(_fromUtf8(""))
        self.edtLocation.setObjectName(_fromUtf8("edtLocation"))
        self.verticalLayout_8.addWidget(self.edtLocation)
        self.layJobData.addLayout(self.verticalLayout_8)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("color:#888"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_6.addWidget(self.label_3)
        self.edtServiceOrder = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtServiceOrder.sizePolicy().hasHeightForWidth())
        self.edtServiceOrder.setSizePolicy(sizePolicy)
        self.edtServiceOrder.setMouseTracking(False)
        self.edtServiceOrder.setAutoFillBackground(False)
        self.edtServiceOrder.setStyleSheet(_fromUtf8("background-color:black; color:white; font-size:12pt; border:  1px solid #888"))
        self.edtServiceOrder.setAlignment(QtCore.Qt.AlignCenter)
        self.edtServiceOrder.setPlaceholderText(_fromUtf8(""))
        self.edtServiceOrder.setObjectName(_fromUtf8("edtServiceOrder"))
        self.verticalLayout_6.addWidget(self.edtServiceOrder)
        self.layJobData.addLayout(self.verticalLayout_6)
        self.gridLayout_2.addLayout(self.layJobData, 0, 0, 1, 1)
        self.layLCDs = QtGui.QHBoxLayout()
        self.layLCDs.setSpacing(3)
        self.layLCDs.setObjectName(_fromUtf8("layLCDs"))
        self.lcd1 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd1.sizePolicy().hasHeightForWidth())
        self.lcd1.setSizePolicy(sizePolicy)
        self.lcd1.setObjectName(_fromUtf8("lcd1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.lcd1)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lcdNumber1 = QtGui.QLCDNumber(self.lcd1)
        self.lcdNumber1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber1.sizePolicy().hasHeightForWidth())
        self.lcdNumber1.setSizePolicy(sizePolicy)
        self.lcdNumber1.setMinimumSize(QtCore.QSize(0, 40))
        self.lcdNumber1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lcdNumber1.setStyleSheet(_fromUtf8("background-color:black; color: #C00;"))
        self.lcdNumber1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber1.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber1.setSmallDecimalPoint(False)
        self.lcdNumber1.setNumDigits(12)
        self.lcdNumber1.setDigitCount(12)
        self.lcdNumber1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber1.setProperty("value", 0.0)
        self.lcdNumber1.setProperty("intValue", 0)
        self.lcdNumber1.setObjectName(_fromUtf8("lcdNumber1"))
        self.verticalLayout.addWidget(self.lcdNumber1)
        self.cmbDigital1 = QtGui.QComboBox(self.lcd1)
        self.cmbDigital1.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #888}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444}\n"
"QComboBox::drop-down {border: 0px}"))
        self.cmbDigital1.setEditable(False)
        self.cmbDigital1.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cmbDigital1.setObjectName(_fromUtf8("cmbDigital1"))
        self.verticalLayout.addWidget(self.cmbDigital1)
        self.layLCDs.addWidget(self.lcd1)
        self.lcd2 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd2.sizePolicy().hasHeightForWidth())
        self.lcd2.setSizePolicy(sizePolicy)
        self.lcd2.setObjectName(_fromUtf8("lcd2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.lcd2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lcdNumber2 = QtGui.QLCDNumber(self.lcd2)
        self.lcdNumber2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber2.sizePolicy().hasHeightForWidth())
        self.lcdNumber2.setSizePolicy(sizePolicy)
        self.lcdNumber2.setMinimumSize(QtCore.QSize(0, 40))
        self.lcdNumber2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcdNumber2.setFont(font)
        self.lcdNumber2.setStyleSheet(_fromUtf8("background-color:black; color: #C00;"))
        self.lcdNumber2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber2.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber2.setLineWidth(1)
        self.lcdNumber2.setSmallDecimalPoint(False)
        self.lcdNumber2.setNumDigits(12)
        self.lcdNumber2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber2.setProperty("value", 0.0)
        self.lcdNumber2.setProperty("intValue", 0)
        self.lcdNumber2.setObjectName(_fromUtf8("lcdNumber2"))
        self.verticalLayout_2.addWidget(self.lcdNumber2)
        self.cmbDigital2 = QtGui.QComboBox(self.lcd2)
        self.cmbDigital2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cmbDigital2.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #888}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444}\n"
"QComboBox::drop-down {border: 0px}"))
        self.cmbDigital2.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cmbDigital2.setObjectName(_fromUtf8("cmbDigital2"))
        self.verticalLayout_2.addWidget(self.cmbDigital2)
        self.layLCDs.addWidget(self.lcd2)
        self.lcd3 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd3.sizePolicy().hasHeightForWidth())
        self.lcd3.setSizePolicy(sizePolicy)
        self.lcd3.setObjectName(_fromUtf8("lcd3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.lcd3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lcdNumber3 = QtGui.QLCDNumber(self.lcd3)
        self.lcdNumber3.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber3.sizePolicy().hasHeightForWidth())
        self.lcdNumber3.setSizePolicy(sizePolicy)
        self.lcdNumber3.setMinimumSize(QtCore.QSize(0, 40))
        self.lcdNumber3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcdNumber3.setFont(font)
        self.lcdNumber3.setStyleSheet(_fromUtf8("background-color:black; color: #C00;"))
        self.lcdNumber3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber3.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber3.setLineWidth(1)
        self.lcdNumber3.setSmallDecimalPoint(False)
        self.lcdNumber3.setNumDigits(12)
        self.lcdNumber3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber3.setProperty("value", 0.0)
        self.lcdNumber3.setProperty("intValue", 0)
        self.lcdNumber3.setObjectName(_fromUtf8("lcdNumber3"))
        self.verticalLayout_3.addWidget(self.lcdNumber3)
        self.cmbDigital3 = QtGui.QComboBox(self.lcd3)
        self.cmbDigital3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cmbDigital3.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #888}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444}\n"
"QComboBox::drop-down {border: 0px}"))
        self.cmbDigital3.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cmbDigital3.setObjectName(_fromUtf8("cmbDigital3"))
        self.verticalLayout_3.addWidget(self.cmbDigital3)
        self.layLCDs.addWidget(self.lcd3)
        self.lcd4 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd4.sizePolicy().hasHeightForWidth())
        self.lcd4.setSizePolicy(sizePolicy)
        self.lcd4.setObjectName(_fromUtf8("lcd4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.lcd4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lcdNumber4 = QtGui.QLCDNumber(self.lcd4)
        self.lcdNumber4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber4.sizePolicy().hasHeightForWidth())
        self.lcdNumber4.setSizePolicy(sizePolicy)
        self.lcdNumber4.setMinimumSize(QtCore.QSize(0, 40))
        self.lcdNumber4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcdNumber4.setFont(font)
        self.lcdNumber4.setStyleSheet(_fromUtf8("background-color:black; color: #C00;"))
        self.lcdNumber4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber4.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber4.setLineWidth(1)
        self.lcdNumber4.setSmallDecimalPoint(False)
        self.lcdNumber4.setNumDigits(12)
        self.lcdNumber4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber4.setProperty("value", 0.0)
        self.lcdNumber4.setProperty("intValue", 0)
        self.lcdNumber4.setObjectName(_fromUtf8("lcdNumber4"))
        self.verticalLayout_4.addWidget(self.lcdNumber4)
        self.cmbDigital4 = QtGui.QComboBox(self.lcd4)
        self.cmbDigital4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cmbDigital4.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #888}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444}\n"
"QComboBox::drop-down {border: 0px}"))
        self.cmbDigital4.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cmbDigital4.setObjectName(_fromUtf8("cmbDigital4"))
        self.verticalLayout_4.addWidget(self.cmbDigital4)
        self.layLCDs.addWidget(self.lcd4)
        self.lcd5 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd5.sizePolicy().hasHeightForWidth())
        self.lcd5.setSizePolicy(sizePolicy)
        self.lcd5.setObjectName(_fromUtf8("lcd5"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.lcd5)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setSpacing(3)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.lcdNumber5 = QtGui.QLCDNumber(self.lcd5)
        self.lcdNumber5.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber5.sizePolicy().hasHeightForWidth())
        self.lcdNumber5.setSizePolicy(sizePolicy)
        self.lcdNumber5.setMinimumSize(QtCore.QSize(0, 40))
        self.lcdNumber5.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcdNumber5.setFont(font)
        self.lcdNumber5.setStyleSheet(_fromUtf8("background-color:black; color: #C00;"))
        self.lcdNumber5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber5.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber5.setLineWidth(1)
        self.lcdNumber5.setSmallDecimalPoint(False)
        self.lcdNumber5.setNumDigits(12)
        self.lcdNumber5.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber5.setProperty("value", 0.0)
        self.lcdNumber5.setProperty("intValue", 0)
        self.lcdNumber5.setObjectName(_fromUtf8("lcdNumber5"))
        self.verticalLayout_15.addWidget(self.lcdNumber5)
        self.cmbDigital5 = QtGui.QComboBox(self.lcd5)
        self.cmbDigital5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cmbDigital5.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #888}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444}\n"
"QComboBox::drop-down {border: 0px}"))
        self.cmbDigital5.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cmbDigital5.setObjectName(_fromUtf8("cmbDigital5"))
        self.verticalLayout_15.addWidget(self.cmbDigital5)
        self.layLCDs.addWidget(self.lcd5)
        self.lcd6 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd6.sizePolicy().hasHeightForWidth())
        self.lcd6.setSizePolicy(sizePolicy)
        self.lcd6.setObjectName(_fromUtf8("lcd6"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.lcd6)
        self.verticalLayout_18.setMargin(0)
        self.verticalLayout_18.setSpacing(3)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.lcdNumber6 = QtGui.QLCDNumber(self.lcd6)
        self.lcdNumber6.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber6.sizePolicy().hasHeightForWidth())
        self.lcdNumber6.setSizePolicy(sizePolicy)
        self.lcdNumber6.setMinimumSize(QtCore.QSize(0, 40))
        self.lcdNumber6.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcdNumber6.setFont(font)
        self.lcdNumber6.setStyleSheet(_fromUtf8("background-color:black; color: #C00;"))
        self.lcdNumber6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber6.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber6.setLineWidth(1)
        self.lcdNumber6.setSmallDecimalPoint(False)
        self.lcdNumber6.setNumDigits(12)
        self.lcdNumber6.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber6.setProperty("value", 0.0)
        self.lcdNumber6.setProperty("intValue", 0)
        self.lcdNumber6.setObjectName(_fromUtf8("lcdNumber6"))
        self.verticalLayout_18.addWidget(self.lcdNumber6)
        self.cmbDigital6 = QtGui.QComboBox(self.lcd6)
        self.cmbDigital6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cmbDigital6.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #888}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444}\n"
"QComboBox::drop-down {border: 0px}"))
        self.cmbDigital6.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cmbDigital6.setObjectName(_fromUtf8("cmbDigital6"))
        self.verticalLayout_18.addWidget(self.cmbDigital6)
        self.layLCDs.addWidget(self.lcd6)
        self.lcd7 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd7.sizePolicy().hasHeightForWidth())
        self.lcd7.setSizePolicy(sizePolicy)
        self.lcd7.setObjectName(_fromUtf8("lcd7"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.lcd7)
        self.verticalLayout_17.setMargin(0)
        self.verticalLayout_17.setSpacing(3)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.lcdNumber7 = QtGui.QLCDNumber(self.lcd7)
        self.lcdNumber7.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber7.sizePolicy().hasHeightForWidth())
        self.lcdNumber7.setSizePolicy(sizePolicy)
        self.lcdNumber7.setMinimumSize(QtCore.QSize(0, 40))
        self.lcdNumber7.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcdNumber7.setFont(font)
        self.lcdNumber7.setStyleSheet(_fromUtf8("background-color:black; color: #C00;"))
        self.lcdNumber7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber7.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber7.setLineWidth(1)
        self.lcdNumber7.setSmallDecimalPoint(False)
        self.lcdNumber7.setNumDigits(12)
        self.lcdNumber7.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber7.setProperty("value", 0.0)
        self.lcdNumber7.setProperty("intValue", 0)
        self.lcdNumber7.setObjectName(_fromUtf8("lcdNumber7"))
        self.verticalLayout_17.addWidget(self.lcdNumber7)
        self.cmbDigital7 = QtGui.QComboBox(self.lcd7)
        self.cmbDigital7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cmbDigital7.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #888}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444}\n"
"QComboBox::drop-down {border: 0px}"))
        self.cmbDigital7.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cmbDigital7.setObjectName(_fromUtf8("cmbDigital7"))
        self.verticalLayout_17.addWidget(self.cmbDigital7)
        self.layLCDs.addWidget(self.lcd7)
        self.lcd8 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd8.sizePolicy().hasHeightForWidth())
        self.lcd8.setSizePolicy(sizePolicy)
        self.lcd8.setObjectName(_fromUtf8("lcd8"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.lcd8)
        self.verticalLayout_16.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setSpacing(3)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.lcdNumber8 = QtGui.QLCDNumber(self.lcd8)
        self.lcdNumber8.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber8.sizePolicy().hasHeightForWidth())
        self.lcdNumber8.setSizePolicy(sizePolicy)
        self.lcdNumber8.setMinimumSize(QtCore.QSize(0, 40))
        self.lcdNumber8.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcdNumber8.setFont(font)
        self.lcdNumber8.setStyleSheet(_fromUtf8("background-color:black; color: #C00;"))
        self.lcdNumber8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber8.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber8.setLineWidth(1)
        self.lcdNumber8.setSmallDecimalPoint(False)
        self.lcdNumber8.setNumDigits(12)
        self.lcdNumber8.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber8.setProperty("value", 0.0)
        self.lcdNumber8.setProperty("intValue", 0)
        self.lcdNumber8.setObjectName(_fromUtf8("lcdNumber8"))
        self.verticalLayout_16.addWidget(self.lcdNumber8)
        self.cmbDigital8 = QtGui.QComboBox(self.lcd8)
        self.cmbDigital8.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #888}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444}\n"
"QComboBox::drop-down {border: 0px}"))
        self.cmbDigital8.setEditable(False)
        self.cmbDigital8.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cmbDigital8.setObjectName(_fromUtf8("cmbDigital8"))
        self.verticalLayout_16.addWidget(self.cmbDigital8)
        self.layLCDs.addWidget(self.lcd8)
        self.gridLayout_2.addLayout(self.layLCDs, 1, 0, 1, 1)
        self.chart1 = PlotWidget(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.chart1.setPalette(palette)
        self.chart1.setStyleSheet(_fromUtf8("border: 1px solid #800"))
        self.chart1.setFrameShadow(QtGui.QFrame.Plain)
        self.chart1.setInteractive(True)
        self.chart1.setObjectName(_fromUtf8("chart1"))
        self.gridLayout_2.addWidget(self.chart1, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cmbPlot1a = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPlot1a.sizePolicy().hasHeightForWidth())
        self.cmbPlot1a.setSizePolicy(sizePolicy)
        self.cmbPlot1a.setMinimumSize(QtCore.QSize(50, 0))
        self.cmbPlot1a.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cmbPlot1a.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #FFA020}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444; ; border: 1px solid #FFA020}\n"
"QComboBox::drop-down {border: 0px}\n"
"QComboBox QAbstractItemView {min-width:229px}"))
        self.cmbPlot1a.setObjectName(_fromUtf8("cmbPlot1a"))
        self.horizontalLayout.addWidget(self.cmbPlot1a)
        self.cmbPlot1b = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPlot1b.sizePolicy().hasHeightForWidth())
        self.cmbPlot1b.setSizePolicy(sizePolicy)
        self.cmbPlot1b.setMinimumSize(QtCore.QSize(50, 0))
        self.cmbPlot1b.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cmbPlot1b.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #A00000}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444; border: 1px solid #A00000}\n"
"QComboBox::drop-down {border: 0px}\n"
"QComboBox QAbstractItemView {min-width:229px}"))
        self.cmbPlot1b.setObjectName(_fromUtf8("cmbPlot1b"))
        self.horizontalLayout.addWidget(self.cmbPlot1b)
        self.cmbPlot1c = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPlot1c.sizePolicy().hasHeightForWidth())
        self.cmbPlot1c.setSizePolicy(sizePolicy)
        self.cmbPlot1c.setMinimumSize(QtCore.QSize(50, 0))
        self.cmbPlot1c.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cmbPlot1c.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #8000FF}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444; border: 1px solid #8000FF}\n"
"QComboBox::drop-down {border: 0px}\n"
"QComboBox QAbstractItemView {min-width:229px}"))
        self.cmbPlot1c.setObjectName(_fromUtf8("cmbPlot1c"))
        self.horizontalLayout.addWidget(self.cmbPlot1c)
        self.ch1shuttle = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch1shuttle.sizePolicy().hasHeightForWidth())
        self.ch1shuttle.setSizePolicy(sizePolicy)
        self.ch1shuttle.setObjectName(_fromUtf8("ch1shuttle"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.ch1shuttle)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnAutoY1 = QtGui.QToolButton(self.ch1shuttle)
        self.btnAutoY1.setEnabled(True)
        self.btnAutoY1.setMinimumSize(QtCore.QSize(45, 0))
        self.btnAutoY1.setMaximumSize(QtCore.QSize(45, 16777215))
        self.btnAutoY1.setStyleSheet(_fromUtf8(":enabled {color:#AAA} :disabled {color:#555}"))
        self.btnAutoY1.setObjectName(_fromUtf8("btnAutoY1"))
        self.horizontalLayout_2.addWidget(self.btnAutoY1)
        spacerItem = QtGui.QSpacerItem(10, 17, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnCh130min = QtGui.QToolButton(self.ch1shuttle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCh130min.sizePolicy().hasHeightForWidth())
        self.btnCh130min.setSizePolicy(sizePolicy)
        self.btnCh130min.setMinimumSize(QtCore.QSize(30, 0))
        self.btnCh130min.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnCh130min.setStyleSheet(_fromUtf8(":enabled {color:#AAA} :disabled {color:#555}"))
        self.btnCh130min.setObjectName(_fromUtf8("btnCh130min"))
        self.horizontalLayout_2.addWidget(self.btnCh130min)
        self.btnCh110min = QtGui.QToolButton(self.ch1shuttle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCh110min.sizePolicy().hasHeightForWidth())
        self.btnCh110min.setSizePolicy(sizePolicy)
        self.btnCh110min.setMinimumSize(QtCore.QSize(30, 0))
        self.btnCh110min.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnCh110min.setStyleSheet(_fromUtf8(":enabled {color:#AAA} :disabled {color:#555}"))
        self.btnCh110min.setObjectName(_fromUtf8("btnCh110min"))
        self.horizontalLayout_2.addWidget(self.btnCh110min)
        self.btnCh15min = QtGui.QToolButton(self.ch1shuttle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCh15min.sizePolicy().hasHeightForWidth())
        self.btnCh15min.setSizePolicy(sizePolicy)
        self.btnCh15min.setMinimumSize(QtCore.QSize(30, 0))
        self.btnCh15min.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnCh15min.setStyleSheet(_fromUtf8(":enabled {color:#AAA} :disabled {color:#555}"))
        self.btnCh15min.setObjectName(_fromUtf8("btnCh15min"))
        self.horizontalLayout_2.addWidget(self.btnCh15min)
        self.btnCh12min = QtGui.QToolButton(self.ch1shuttle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCh12min.sizePolicy().hasHeightForWidth())
        self.btnCh12min.setSizePolicy(sizePolicy)
        self.btnCh12min.setMinimumSize(QtCore.QSize(30, 0))
        self.btnCh12min.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnCh12min.setStyleSheet(_fromUtf8(":enabled {color:#AAA} :disabled {color:#555}"))
        self.btnCh12min.setObjectName(_fromUtf8("btnCh12min"))
        self.horizontalLayout_2.addWidget(self.btnCh12min)
        self.btnCh11min = QtGui.QToolButton(self.ch1shuttle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCh11min.sizePolicy().hasHeightForWidth())
        self.btnCh11min.setSizePolicy(sizePolicy)
        self.btnCh11min.setMinimumSize(QtCore.QSize(30, 0))
        self.btnCh11min.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnCh11min.setStyleSheet(_fromUtf8(":enabled {color:#AAA} :disabled {color:#555}"))
        self.btnCh11min.setObjectName(_fromUtf8("btnCh11min"))
        self.horizontalLayout_2.addWidget(self.btnCh11min)
        spacerItem1 = QtGui.QSpacerItem(10, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnCh1Pause = QtGui.QToolButton(self.ch1shuttle)
        self.btnCh1Pause.setStyleSheet(_fromUtf8("padding: 0px 2px 1px 3px"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pause off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pause on.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pause off disabled.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pause on disabled.png")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.btnCh1Pause.setIcon(icon)
        self.btnCh1Pause.setIconSize(QtCore.QSize(16, 16))
        self.btnCh1Pause.setCheckable(True)
        self.btnCh1Pause.setChecked(False)
        self.btnCh1Pause.setObjectName(_fromUtf8("btnCh1Pause"))
        self.horizontalLayout_2.addWidget(self.btnCh1Pause)
        spacerItem2 = QtGui.QSpacerItem(10, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btnCh1Export = QtGui.QToolButton(self.ch1shuttle)
        self.btnCh1Export.setStyleSheet(_fromUtf8("padding: 0px 2px 1px 3px"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/export disabled.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.btnCh1Export.setIcon(icon1)
        self.btnCh1Export.setIconSize(QtCore.QSize(16, 16))
        self.btnCh1Export.setCheckable(False)
        self.btnCh1Export.setChecked(False)
        self.btnCh1Export.setObjectName(_fromUtf8("btnCh1Export"))
        self.horizontalLayout_2.addWidget(self.btnCh1Export)
        spacerItem3 = QtGui.QSpacerItem(10, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btnCh1LockY = QtGui.QToolButton(self.ch1shuttle)
        self.btnCh1LockY.setMinimumSize(QtCore.QSize(0, 22))
        self.btnCh1LockY.setStyleSheet(_fromUtf8("padding: 0px 2px 1px 3px; color:#AAA"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/lock off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/lock on.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/lock off disabled.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/lock on disabled.png")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.btnCh1LockY.setIcon(icon2)
        self.btnCh1LockY.setIconSize(QtCore.QSize(20, 16))
        self.btnCh1LockY.setCheckable(True)
        self.btnCh1LockY.setChecked(False)
        self.btnCh1LockY.setObjectName(_fromUtf8("btnCh1LockY"))
        self.horizontalLayout_2.addWidget(self.btnCh1LockY)
        spacerItem4 = QtGui.QSpacerItem(10, 17, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.btnAutoY2 = QtGui.QToolButton(self.ch1shuttle)
        self.btnAutoY2.setEnabled(True)
        self.btnAutoY2.setMinimumSize(QtCore.QSize(45, 0))
        self.btnAutoY2.setMaximumSize(QtCore.QSize(45, 16777215))
        self.btnAutoY2.setStyleSheet(_fromUtf8(":enabled {color:#AAA} :disabled {color:#555}"))
        self.btnAutoY2.setObjectName(_fromUtf8("btnAutoY2"))
        self.horizontalLayout_2.addWidget(self.btnAutoY2)
        self.btnAutoY1.raise_()
        self.btnCh130min.raise_()
        self.btnCh110min.raise_()
        self.btnCh15min.raise_()
        self.btnCh12min.raise_()
        self.btnCh11min.raise_()
        self.btnCh1Pause.raise_()
        self.btnCh1Export.raise_()
        self.btnAutoY2.raise_()
        self.btnCh1LockY.raise_()
        self.horizontalLayout.addWidget(self.ch1shuttle)
        self.cmbPlot2c = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPlot2c.sizePolicy().hasHeightForWidth())
        self.cmbPlot2c.setSizePolicy(sizePolicy)
        self.cmbPlot2c.setMinimumSize(QtCore.QSize(50, 0))
        self.cmbPlot2c.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cmbPlot2c.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #0070FF}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444; border: 1px solid #0070FF}\n"
"QComboBox::drop-down {border: 0px}\n"
"QComboBox QAbstractItemView {min-width:229px}"))
        self.cmbPlot2c.setObjectName(_fromUtf8("cmbPlot2c"))
        self.horizontalLayout.addWidget(self.cmbPlot2c)
        self.cmbPlot2b = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPlot2b.sizePolicy().hasHeightForWidth())
        self.cmbPlot2b.setSizePolicy(sizePolicy)
        self.cmbPlot2b.setMinimumSize(QtCore.QSize(50, 0))
        self.cmbPlot2b.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cmbPlot2b.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #00A000}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444;  border: 1px solid #00A0FF}\n"
"QComboBox::drop-down {border: 0px}\n"
"QComboBox QAbstractItemView {min-width:229px}"))
        self.cmbPlot2b.setObjectName(_fromUtf8("cmbPlot2b"))
        self.horizontalLayout.addWidget(self.cmbPlot2b)
        self.cmbPlot2a = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPlot2a.sizePolicy().hasHeightForWidth())
        self.cmbPlot2a.setSizePolicy(sizePolicy)
        self.cmbPlot2a.setMinimumSize(QtCore.QSize(50, 0))
        self.cmbPlot2a.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cmbPlot2a.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #40C0FF}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444; border: 1px solid #40C0FF}\n"
"QComboBox::drop-down {border: 0px}\n"
"QComboBox QAbstractItemView {min-width:229px}"))
        self.cmbPlot2a.setObjectName(_fromUtf8("cmbPlot2a"))
        self.horizontalLayout.addWidget(self.cmbPlot2a)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.chart2 = PlotWidget(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.chart2.setPalette(palette)
        self.chart2.setStyleSheet(_fromUtf8("border: 1px solid #800"))
        self.chart2.setFrameShadow(QtGui.QFrame.Plain)
        self.chart2.setObjectName(_fromUtf8("chart2"))
        self.gridLayout_2.addWidget(self.chart2, 4, 0, 1, 1)
        self.layAnnotationsRec = QtGui.QHBoxLayout()
        self.layAnnotationsRec.setSpacing(10)
        self.layAnnotationsRec.setObjectName(_fromUtf8("layAnnotationsRec"))
        self.grpAnnotations = QtGui.QGroupBox(self.centralwidget)
        self.grpAnnotations.setEnabled(True)
        self.grpAnnotations.setMinimumSize(QtCore.QSize(0, 61))
        self.grpAnnotations.setStyleSheet(_fromUtf8("QGroupBox{color:#888;border:1px solid #888;margin-top: 8;}\n"
"QGroupBox::title {subcontrol-origin: margin; subcontrol-position: top center}\n"
""))
        self.grpAnnotations.setObjectName(_fromUtf8("grpAnnotations"))
        self.gridLayout = QtGui.QGridLayout(self.grpAnnotations)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnAnn1 = QtGui.QPushButton(self.grpAnnotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAnn1.sizePolicy().hasHeightForWidth())
        self.btnAnn1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnAnn1.setFont(font)
        self.btnAnn1.setStyleSheet(_fromUtf8("color:white"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/star.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAnn1.setIcon(icon3)
        self.btnAnn1.setObjectName(_fromUtf8("btnAnn1"))
        self.horizontalLayout_4.addWidget(self.btnAnn1)
        self.btnAnn2 = QtGui.QPushButton(self.grpAnnotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAnn2.sizePolicy().hasHeightForWidth())
        self.btnAnn2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnAnn2.setFont(font)
        self.btnAnn2.setStyleSheet(_fromUtf8("color:white"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/diamond.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAnn2.setIcon(icon4)
        self.btnAnn2.setObjectName(_fromUtf8("btnAnn2"))
        self.horizontalLayout_4.addWidget(self.btnAnn2)
        self.btnAnn3 = QtGui.QPushButton(self.grpAnnotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAnn3.sizePolicy().hasHeightForWidth())
        self.btnAnn3.setSizePolicy(sizePolicy)
        self.btnAnn3.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnAnn3.setFont(font)
        self.btnAnn3.setStyleSheet(_fromUtf8("color:white"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/circle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAnn3.setIcon(icon5)
        self.btnAnn3.setObjectName(_fromUtf8("btnAnn3"))
        self.horizontalLayout_4.addWidget(self.btnAnn3)
        self.btnAnn4 = QtGui.QPushButton(self.grpAnnotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAnn4.sizePolicy().hasHeightForWidth())
        self.btnAnn4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnAnn4.setFont(font)
        self.btnAnn4.setStyleSheet(_fromUtf8("color:white"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/triangle left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAnn4.setIcon(icon6)
        self.btnAnn4.setObjectName(_fromUtf8("btnAnn4"))
        self.horizontalLayout_4.addWidget(self.btnAnn4)
        self.btnAnn5 = QtGui.QPushButton(self.grpAnnotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAnn5.sizePolicy().hasHeightForWidth())
        self.btnAnn5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnAnn5.setFont(font)
        self.btnAnn5.setStyleSheet(_fromUtf8("color:white"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/triangle up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAnn5.setIcon(icon7)
        self.btnAnn5.setObjectName(_fromUtf8("btnAnn5"))
        self.horizontalLayout_4.addWidget(self.btnAnn5)
        self.btnAnn6 = QtGui.QPushButton(self.grpAnnotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAnn6.sizePolicy().hasHeightForWidth())
        self.btnAnn6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnAnn6.setFont(font)
        self.btnAnn6.setStyleSheet(_fromUtf8("color:white"))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/triangle right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAnn6.setIcon(icon8)
        self.btnAnn6.setObjectName(_fromUtf8("btnAnn6"))
        self.horizontalLayout_4.addWidget(self.btnAnn6)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.layAnnotationsRec.addWidget(self.grpAnnotations)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 61))
        self.groupBox_2.setStyleSheet(_fromUtf8("QGroupBox{color:#888;border:1px solid #888;margin-top: 8;}\n"
"QGroupBox::title {subcontrol-origin: margin; subcontrol-position: top center}\n"
""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.btnRec = QtGui.QToolButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRec.sizePolicy().hasHeightForWidth())
        self.btnRec.setSizePolicy(sizePolicy)
        self.btnRec.setMinimumSize(QtCore.QSize(60, 0))
        self.btnRec.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnRec.setFont(font)
        self.btnRec.setStyleSheet(_fromUtf8("QToolButton:default {color:#FFF;} QToolButton:checked {color:red}"))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/rec off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/rec on.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnRec.setIcon(icon9)
        self.btnRec.setIconSize(QtCore.QSize(24, 24))
        self.btnRec.setCheckable(True)
        self.btnRec.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnRec.setObjectName(_fromUtf8("btnRec"))
        self.horizontalLayout_7.addWidget(self.btnRec)
        self.layAnnotationsRec.addWidget(self.groupBox_2)
        self.gridLayout_2.addLayout(self.layAnnotationsRec, 6, 0, 1, 1)
        self.lblCommError = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCommError.sizePolicy().hasHeightForWidth())
        self.lblCommError.setSizePolicy(sizePolicy)
        self.lblCommError.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblCommError.setFont(font)
        self.lblCommError.setStyleSheet(_fromUtf8("color:white; background-color:darkred"))
        self.lblCommError.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCommError.setObjectName(_fromUtf8("lblCommError"))
        self.gridLayout_2.addWidget(self.lblCommError, 7, 0, 1, 1)
        self.ch2controls = QtGui.QWidget(self.centralwidget)
        self.ch2controls.setObjectName(_fromUtf8("ch2controls"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.ch2controls)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.cmbPlot3a = QtGui.QComboBox(self.ch2controls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPlot3a.sizePolicy().hasHeightForWidth())
        self.cmbPlot3a.setSizePolicy(sizePolicy)
        self.cmbPlot3a.setMinimumSize(QtCore.QSize(50, 0))
        self.cmbPlot3a.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cmbPlot3a.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #FFA020}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444; ; border: 1px solid #FFA020}\n"
"QComboBox::drop-down {border: 0px}\n"
"QComboBox QAbstractItemView {min-width:229px}"))
        self.cmbPlot3a.setObjectName(_fromUtf8("cmbPlot3a"))
        self.horizontalLayout_5.addWidget(self.cmbPlot3a)
        self.cmbPlot3b = QtGui.QComboBox(self.ch2controls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPlot3b.sizePolicy().hasHeightForWidth())
        self.cmbPlot3b.setSizePolicy(sizePolicy)
        self.cmbPlot3b.setMinimumSize(QtCore.QSize(50, 0))
        self.cmbPlot3b.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cmbPlot3b.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #A00000}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444; border: 1px solid #A00000}\n"
"QComboBox::drop-down {border: 0px}\n"
"QComboBox QAbstractItemView {min-width:229px}"))
        self.cmbPlot3b.setObjectName(_fromUtf8("cmbPlot3b"))
        self.horizontalLayout_5.addWidget(self.cmbPlot3b)
        self.cmbPlot3c = QtGui.QComboBox(self.ch2controls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPlot3c.sizePolicy().hasHeightForWidth())
        self.cmbPlot3c.setSizePolicy(sizePolicy)
        self.cmbPlot3c.setMinimumSize(QtCore.QSize(50, 0))
        self.cmbPlot3c.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cmbPlot3c.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #8000FF}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444; border: 1px solid #8000FF}\n"
"QComboBox::drop-down {border: 0px}\n"
"QComboBox QAbstractItemView {min-width:229px}"))
        self.cmbPlot3c.setObjectName(_fromUtf8("cmbPlot3c"))
        self.horizontalLayout_5.addWidget(self.cmbPlot3c)
        self.ch2shuttle = QtGui.QWidget(self.ch2controls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch2shuttle.sizePolicy().hasHeightForWidth())
        self.ch2shuttle.setSizePolicy(sizePolicy)
        self.ch2shuttle.setObjectName(_fromUtf8("ch2shuttle"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.ch2shuttle)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnAutoY3 = QtGui.QToolButton(self.ch2shuttle)
        self.btnAutoY3.setEnabled(True)
        self.btnAutoY3.setMinimumSize(QtCore.QSize(40, 0))
        self.btnAutoY3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnAutoY3.setStyleSheet(_fromUtf8(":enabled {color:#AAA} :disabled {color:#555}"))
        self.btnAutoY3.setObjectName(_fromUtf8("btnAutoY3"))
        self.horizontalLayout_3.addWidget(self.btnAutoY3)
        spacerItem5 = QtGui.QSpacerItem(10, 17, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.btnCh230min = QtGui.QToolButton(self.ch2shuttle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCh230min.sizePolicy().hasHeightForWidth())
        self.btnCh230min.setSizePolicy(sizePolicy)
        self.btnCh230min.setMinimumSize(QtCore.QSize(30, 0))
        self.btnCh230min.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnCh230min.setStyleSheet(_fromUtf8(":enabled {color:#AAA} :disabled {color:#555}"))
        self.btnCh230min.setObjectName(_fromUtf8("btnCh230min"))
        self.horizontalLayout_3.addWidget(self.btnCh230min)
        self.btnCh210min = QtGui.QToolButton(self.ch2shuttle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCh210min.sizePolicy().hasHeightForWidth())
        self.btnCh210min.setSizePolicy(sizePolicy)
        self.btnCh210min.setMinimumSize(QtCore.QSize(30, 0))
        self.btnCh210min.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnCh210min.setStyleSheet(_fromUtf8(":enabled {color:#AAA} :disabled {color:#555}"))
        self.btnCh210min.setObjectName(_fromUtf8("btnCh210min"))
        self.horizontalLayout_3.addWidget(self.btnCh210min)
        self.btnCh25min = QtGui.QToolButton(self.ch2shuttle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCh25min.sizePolicy().hasHeightForWidth())
        self.btnCh25min.setSizePolicy(sizePolicy)
        self.btnCh25min.setMinimumSize(QtCore.QSize(30, 0))
        self.btnCh25min.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnCh25min.setStyleSheet(_fromUtf8(":enabled {color:#AAA} :disabled {color:#555}"))
        self.btnCh25min.setObjectName(_fromUtf8("btnCh25min"))
        self.horizontalLayout_3.addWidget(self.btnCh25min)
        self.btnCh22min = QtGui.QToolButton(self.ch2shuttle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCh22min.sizePolicy().hasHeightForWidth())
        self.btnCh22min.setSizePolicy(sizePolicy)
        self.btnCh22min.setMinimumSize(QtCore.QSize(30, 0))
        self.btnCh22min.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnCh22min.setStyleSheet(_fromUtf8(":enabled {color:#AAA} :disabled {color:#555}"))
        self.btnCh22min.setObjectName(_fromUtf8("btnCh22min"))
        self.horizontalLayout_3.addWidget(self.btnCh22min)
        self.btnCh21min = QtGui.QToolButton(self.ch2shuttle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCh21min.sizePolicy().hasHeightForWidth())
        self.btnCh21min.setSizePolicy(sizePolicy)
        self.btnCh21min.setMinimumSize(QtCore.QSize(30, 0))
        self.btnCh21min.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnCh21min.setStyleSheet(_fromUtf8(":enabled {color:#AAA} :disabled {color:#555}"))
        self.btnCh21min.setObjectName(_fromUtf8("btnCh21min"))
        self.horizontalLayout_3.addWidget(self.btnCh21min)
        spacerItem6 = QtGui.QSpacerItem(10, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.btnCh2Pause = QtGui.QToolButton(self.ch2shuttle)
        self.btnCh2Pause.setStyleSheet(_fromUtf8("padding: 0px 2px 1px 3px"))
        self.btnCh2Pause.setIcon(icon)
        self.btnCh2Pause.setCheckable(True)
        self.btnCh2Pause.setObjectName(_fromUtf8("btnCh2Pause"))
        self.horizontalLayout_3.addWidget(self.btnCh2Pause)
        spacerItem7 = QtGui.QSpacerItem(10, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.btnCh2Export = QtGui.QToolButton(self.ch2shuttle)
        self.btnCh2Export.setStyleSheet(_fromUtf8("padding: 0px 2px 1px 3px"))
        self.btnCh2Export.setIcon(icon1)
        self.btnCh2Export.setIconSize(QtCore.QSize(16, 16))
        self.btnCh2Export.setCheckable(False)
        self.btnCh2Export.setChecked(False)
        self.btnCh2Export.setObjectName(_fromUtf8("btnCh2Export"))
        self.horizontalLayout_3.addWidget(self.btnCh2Export)
        spacerItem8 = QtGui.QSpacerItem(10, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.btnCh2LockY = QtGui.QToolButton(self.ch2shuttle)
        self.btnCh2LockY.setMinimumSize(QtCore.QSize(0, 22))
        self.btnCh2LockY.setStyleSheet(_fromUtf8("padding: 0px 2px 1px 3px; color:#AAA"))
        self.btnCh2LockY.setIcon(icon2)
        self.btnCh2LockY.setIconSize(QtCore.QSize(20, 16))
        self.btnCh2LockY.setCheckable(True)
        self.btnCh2LockY.setChecked(False)
        self.btnCh2LockY.setObjectName(_fromUtf8("btnCh2LockY"))
        self.horizontalLayout_3.addWidget(self.btnCh2LockY)
        spacerItem9 = QtGui.QSpacerItem(10, 17, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.btnAutoY4 = QtGui.QToolButton(self.ch2shuttle)
        self.btnAutoY4.setEnabled(True)
        self.btnAutoY4.setMinimumSize(QtCore.QSize(40, 0))
        self.btnAutoY4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnAutoY4.setStyleSheet(_fromUtf8(":enabled {color:#AAA} :disabled {color:#555}"))
        self.btnAutoY4.setObjectName(_fromUtf8("btnAutoY4"))
        self.horizontalLayout_3.addWidget(self.btnAutoY4)
        self.horizontalLayout_5.addWidget(self.ch2shuttle)
        self.cmbPlot4c = QtGui.QComboBox(self.ch2controls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPlot4c.sizePolicy().hasHeightForWidth())
        self.cmbPlot4c.setSizePolicy(sizePolicy)
        self.cmbPlot4c.setMinimumSize(QtCore.QSize(50, 0))
        self.cmbPlot4c.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cmbPlot4c.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #0070FF}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444; border: 1px solid #0070FF}\n"
"QComboBox::drop-down {border: 0px}\n"
"QComboBox QAbstractItemView {min-width:229px}"))
        self.cmbPlot4c.setObjectName(_fromUtf8("cmbPlot4c"))
        self.horizontalLayout_5.addWidget(self.cmbPlot4c)
        self.cmbPlot4b = QtGui.QComboBox(self.ch2controls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPlot4b.sizePolicy().hasHeightForWidth())
        self.cmbPlot4b.setSizePolicy(sizePolicy)
        self.cmbPlot4b.setMinimumSize(QtCore.QSize(50, 0))
        self.cmbPlot4b.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cmbPlot4b.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #00A000}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444;  border: 1px solid #00A0FF}\n"
"QComboBox::drop-down {border: 0px}\n"
"QComboBox QAbstractItemView {min-width:229px}"))
        self.cmbPlot4b.setObjectName(_fromUtf8("cmbPlot4b"))
        self.horizontalLayout_5.addWidget(self.cmbPlot4b)
        self.cmbPlot4a = QtGui.QComboBox(self.ch2controls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPlot4a.sizePolicy().hasHeightForWidth())
        self.cmbPlot4a.setSizePolicy(sizePolicy)
        self.cmbPlot4a.setMinimumSize(QtCore.QSize(50, 0))
        self.cmbPlot4a.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cmbPlot4a.setStyleSheet(_fromUtf8("QComboBox {background-color: black; color:#888;font-size:10pt; border: 1px solid #40C0FF}\n"
"QComboBox QAbstractItemView {background-color: black; color: #888; selection-background-color: #444; border: 1px solid #40C0FF}\n"
"QComboBox::drop-down {border: 0px}\n"
"QComboBox QAbstractItemView {min-width:229px}"))
        self.cmbPlot4a.setObjectName(_fromUtf8("cmbPlot4a"))
        self.horizontalLayout_5.addWidget(self.cmbPlot4a)
        self.gridLayout_2.addWidget(self.ch2controls, 5, 0, 1, 1)
        self.ch2controls.raise_()
        self.lblCommError.raise_()
        self.chart1.raise_()
        self.chart2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 950, 21))
        self.menuBar.setStyleSheet(_fromUtf8(":item {background-color:#333; color:white} :item:selected {background-color:#444} :item:disabled {color:#888}"))
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuMenu = QtGui.QMenu(self.menuBar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionExport_PDF = QtGui.QAction(MainWindow)
        self.actionExport_PDF.setObjectName(_fromUtf8("actionExport_PDF"))
        self.actionLoad_Configuration = QtGui.QAction(MainWindow)
        self.actionLoad_Configuration.setObjectName(_fromUtf8("actionLoad_Configuration"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionReset_Totalisers = QtGui.QAction(MainWindow)
        self.actionReset_Totalisers.setObjectName(_fromUtf8("actionReset_Totalisers"))
        self.actionTwo_Charts = QtGui.QAction(MainWindow)
        self.actionTwo_Charts.setCheckable(True)
        self.actionTwo_Charts.setChecked(True)
        self.actionTwo_Charts.setObjectName(_fromUtf8("actionTwo_Charts"))
        self.actionLock_X_Axes = QtGui.QAction(MainWindow)
        self.actionLock_X_Axes.setCheckable(True)
        self.actionLock_X_Axes.setEnabled(True)
        self.actionLock_X_Axes.setObjectName(_fromUtf8("actionLock_X_Axes"))
        self.actionExport_PNG = QtGui.QAction(MainWindow)
        self.actionExport_PNG.setObjectName(_fromUtf8("actionExport_PNG"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionStart_recording = QtGui.QAction(MainWindow)
        self.actionStart_recording.setObjectName(_fromUtf8("actionStart_recording"))
        self.actionStop_recording = QtGui.QAction(MainWindow)
        self.actionStop_recording.setObjectName(_fromUtf8("actionStop_recording"))
        self.actionSetup = QtGui.QAction(MainWindow)
        self.actionSetup.setObjectName(_fromUtf8("actionSetup"))
        self.menuMenu.addAction(self.actionTwo_Charts)
        self.menuMenu.addAction(self.actionLock_X_Axes)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionReset_Totalisers)
        self.menuMenu.addSeparator()
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionAbout)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menuBar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.edtCustomerName, self.edtLocation)
        MainWindow.setTabOrder(self.edtLocation, self.edtServiceOrder)
        MainWindow.setTabOrder(self.edtServiceOrder, self.edtDate)
        MainWindow.setTabOrder(self.edtDate, self.btnAnn1)
        MainWindow.setTabOrder(self.btnAnn1, self.btnAnn2)
        MainWindow.setTabOrder(self.btnAnn2, self.btnAnn3)
        MainWindow.setTabOrder(self.btnAnn3, self.btnAnn4)
        MainWindow.setTabOrder(self.btnAnn4, self.btnAnn5)
        MainWindow.setTabOrder(self.btnAnn5, self.btnAnn6)
        MainWindow.setTabOrder(self.btnAnn6, self.cmbDigital1)
        MainWindow.setTabOrder(self.cmbDigital1, self.cmbDigital8)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Core Completions Datalogger", None))
        self.label_4.setText(_translate("MainWindow", "Date", None))
        self.edtDate.setDisplayFormat(_translate("MainWindow", "dd MMM yyyy", None))
        self.label.setText(_translate("MainWindow", "Customer", None))
        self.label_2.setText(_translate("MainWindow", "Location", None))
        self.label_3.setText(_translate("MainWindow", "Service Order #", None))
        self.btnAutoY1.setText(_translate("MainWindow", "Auto Y", None))
        self.btnCh130min.setText(_translate("MainWindow", "30m", None))
        self.btnCh110min.setText(_translate("MainWindow", "10m", None))
        self.btnCh15min.setText(_translate("MainWindow", "5m", None))
        self.btnCh12min.setText(_translate("MainWindow", "2m", None))
        self.btnCh11min.setText(_translate("MainWindow", "1m", None))
        self.btnCh1Pause.setText(_translate("MainWindow", "...", None))
        self.btnCh1Export.setText(_translate("MainWindow", "...", None))
        self.btnCh1LockY.setText(_translate("MainWindow", "Y", None))
        self.btnAutoY2.setText(_translate("MainWindow", "Auto Y", None))
        self.grpAnnotations.setTitle(_translate("MainWindow", " Annotations ", None))
        self.btnAnn1.setText(_translate("MainWindow", "Job Started", None))
        self.btnAnn2.setText(_translate("MainWindow", "Pressure Test", None))
        self.btnAnn3.setText(_translate("MainWindow", "Reverse Circulate", None))
        self.btnAnn4.setText(_translate("MainWindow", "Custom 1", None))
        self.btnAnn5.setText(_translate("MainWindow", "Custom 2", None))
        self.btnAnn6.setText(_translate("MainWindow", "Custom 3", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Log File", None))
        self.btnRec.setText(_translate("MainWindow", "REC", None))
        self.lblCommError.setText(_translate("MainWindow", "Server is not responding", None))
        self.btnAutoY3.setText(_translate("MainWindow", "Auto Y", None))
        self.btnCh230min.setText(_translate("MainWindow", "30m", None))
        self.btnCh210min.setText(_translate("MainWindow", "10m", None))
        self.btnCh25min.setText(_translate("MainWindow", "5m", None))
        self.btnCh22min.setText(_translate("MainWindow", "2m", None))
        self.btnCh21min.setText(_translate("MainWindow", "1m", None))
        self.btnCh2Pause.setText(_translate("MainWindow", "...", None))
        self.btnCh2Export.setText(_translate("MainWindow", "...", None))
        self.btnCh2LockY.setText(_translate("MainWindow", "Y", None))
        self.btnAutoY4.setText(_translate("MainWindow", "Auto Y", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.actionSave.setText(_translate("MainWindow", "Save Configuration", None))
        self.actionExport_PDF.setText(_translate("MainWindow", "Export PDF", None))
        self.actionLoad_Configuration.setText(_translate("MainWindow", "Load Configuration", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionReset_Totalisers.setText(_translate("MainWindow", "Reset Totalisers", None))
        self.actionReset_Totalisers.setShortcut(_translate("MainWindow", "Alt+R", None))
        self.actionTwo_Charts.setText(_translate("MainWindow", "Two Charts", None))
        self.actionTwo_Charts.setShortcut(_translate("MainWindow", "Alt+2", None))
        self.actionLock_X_Axes.setText(_translate("MainWindow", "Lock X-Axes", None))
        self.actionLock_X_Axes.setShortcut(_translate("MainWindow", "Alt+L", None))
        self.actionExport_PNG.setText(_translate("MainWindow", "Export PNG", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionStart_recording.setText(_translate("MainWindow", "Start recording", None))
        self.actionStop_recording.setText(_translate("MainWindow", "Stop recording", None))
        self.actionSetup.setText(_translate("MainWindow", "Setup ...", None))

from chart import PlotWidget
import resources_rc
